### ISSUE TITLE
Image not shown

### ISSUE THREAD

**Issue by germa89** [akaszynski/akaszynski#3]
Image:

![image](https://github.com/akaszynski/akaszynski/assets/28149841/b2c468bd-eb64-4bcc-b8ae-7ac10305d301)

I believe the problem is in this line:
https://github.com/akaszynski/akaszynski/blob/3c24500303074fd63e6b58cf2a823475f8d344f9/README.md?plain=1#L97

**Comment by germa89** [comment]
Pinging @akaszynski

**Comment by akaszynski** [comment]
Resolved in [e67df87](https://github.com/akaszynski/akaszynski/commit/e67df871235bbbc17e49a33383a4f3d00d6a9d3c). Looks like they changed their URL. Thanks for pointing that out!
